name: Event Generation and Simulation
on: push
jobs:
  sim:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kkrizka/mcprod:pr-4
    steps:
      -
        name: Checkout        
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Generate GridPacks
        run: |
          ./makeGridPacks.py 13 B 1
          /opt/MG5aMC/3.3.1/bin/mg5_aMC < run/makeGridPacks.mg
          tar -xzvf 13TeV_B/run_01_gridpack.tar.gz
          cd madevent
          ./bin/compile
          ./bin/clean4grid
          ./bin/gridrun 1000 0 1
