name: Event Generation and Simulation
on: push
jobs:
  sim:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kkrizka/MCProd:pr-4
    steps:
      -
        name: Checkout        
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Generate GridPacks
        run: testGridpacks.sh
